### ISSUE TITLE
AttributeError: 'str' object has no attribute 'annotation'

### ISSUE THREAD

**Issue by wwang-nmdp** [nmdp-bioinformatics/py-gfe#23]
`Traceback (most recent call last):
  File "/usr/local/bin/seq2gfe", line 94, in <module>
    main()
  File "/usr/local/bin/seq2gfe", line 76, in main
    features, gfe = gfe_maker.get_gfe(ann, loc)
  File "/usr/local/lib/python3.6/dist-packages/pygfe/pygfe.py", line 104, in get_gfe
    for feat in annotation.annotation:
AttributeError: 'str' object has no attribute 'annotation'`

**Comment by mmaiers-nmdp** [comment]
closed
