### ISSUE TITLE
Documentation updates please

### ISSUE THREAD

**Issue by jbrelsf2-nmdp** [nmdp-bioinformatics/py-gfe#27]
Using the docs:  https://pygfe.readthedocs.io/en/latest/readme.html  I'm unable to run through the example code.

Building and running in local python 3.7 env.

from Bio import SeqIO
from BioSQL import BioSeqDatabase
from seqann.sequence_annotation import BioSeqAnn
import pygfe
seq_file = 'DQB1_gen.fasta'
gfe = pygfe.pyGFE()
server = BioSeqDatabase.open_database(driver="pymysql", user="root", passwd="my-secret-pw", host="localhost", db="bioseqdb")
seqann = BioSeqAnn(server=server)
seq_rec = list(SeqIO.parse(seq_file, 'fasta'))[0]
annotation = seqann.annotate(seq_rec, "HLA-DQB1")
#gfe = gfe.gfe_create("HLA-DQB1", "DQB1_gen.fasta", '3220_DQB1')
gfe = gfe.sequence_lookup("HLA-DQB1", "DQB1_gen.fasta", '3220_DQB1')
print(gfe)

Error:
Traceback (most recent call last):
  File "run-sample.py", line 12, in <module>
    gfe = gfe.sequence_lookup("HLA-DQB1", "DQB1_gen.fasta", '3220_DQB1')
  File "/Users/jbrelsf2/Documents/sandbox/pyGFE/pygfe/pygfe.py", line 357, in sequence_lookup
    sequence_data = self.graph.run(lookup_query).to_data_frame()
AttributeError: 'NoneType' object has no attribute 'run'

**Comment by mhalagan** [comment]
It looks like that's an outdated example. The documentation for this package is pretty terrible.  In order for this example to work, you need to initalize the pygfe class with a py2neo `Graph` object (ex. `pygfe.pyGFE(graph=graph)`). If you initialize `BioSeqAnn`with a server, then you need to make sure that server is running locally.
