### ISSUE TITLE
Error message from annotating HLA-DPB1

### ISSUE THREAD

**Issue by wwang-nmdp** [nmdp-bioinformatics/py-gfe#29]
Traceback (most recent call last):
  File "/gfe/seq2gfe", line 88, in <module>
    main()
  File "/gfe/seq2gfe", line 67, in main
    ann = seqann.annotate(seq, loc)
  File "/usr/local/lib/python3.7/site-packages/seqann/sequence_annotation.py", line 469, in annotate
    cutoff=align_cutoff)
  File "/usr/local/lib/python3.7/site-packages/seqann/sequence_annotation.py", line 711, in ref_align
    verbosity=self.align_verbosity)
  File "/usr/local/lib/python3.7/site-packages/seqann/align.py", line 175, in align_seqs
    verbosity)
  File "/usr/local/lib/python3.7/site-packages/seqann/align.py", line 348, in resolve_feats
    strand=1), type=f.type)
  File "/usr/local/lib/python3.7/site-packages/Bio/SeqFeature.py", line 761, in __init__
    self.start))
ValueError: End location (18) must be greater than or equal to start location (100)

> test-dpb1
TCCGCCCCCTCCCCGCAGAGAATTACGTGTACCAGTTACGGCAGGAATGCTACGCGTTTAATGGGACACAGCGCTTCCTGGAGAGATACATCTACAACCGGCAGGAGTACGCGCGCTTCGACAGCGACGTGGGAGAGTTCCGGGCGGTGACGGAGCTGGGGCGGCCTGCTGCGGAGTACTGGAACAGCCAGAAGGACCTCCTGGAGGAGAGGCGGGCAGTGCCGGACAGGATGTGCAGACACAACTACGAGCTGGACGAGGCCGTGACCCTGCAGCGCCGAGGTGAGTGAGGGCTTTGGGCCGGCGGTCCCAGGGCAGCCCCGCGGGCCCGTGCCCAGGGCGCAGGAGCAGCCGGGTTGGCCTAAGGGACCTTAGTGCCGGGCGGAAAGGGGACTTTGGGTTGGGGATTCATGGGGGGAGCCCATCTGGAGCTTGTCAGGGGAGCGAGCGCGGGGACCTGGACTGGGCTGAGCATGGAGTGAGGAGGACGGGAGCAGAGAGACCCCGGGGACTTCATCAGGCCTGGCAGCTGACTGCATGTGGGGTGAAAAAAAGGAAGCCACAGGACAGCGCACAAGGGTATGGTGTGGAGATGGAGGTGGAGATGGCACAGCAGGCCACACAGAGAAGAAACCTACAGGGAGTTAGCTGGGTTTGAGGTGCTTGAGGGGCAGATGGGTGGTCTGATGGGCAGGTAGACAGAAGGGTCTGCAGCCGGGGAGGAGACTGAGATACATGAGACCATCCAGGGAGAGGGGACCCAGGGGGAAGAGCAAAGGACTGGATCCTGGGAACTGGACAGTTGTGATTTGGCCAAGACAGAAAAGCCTGTGAAAGAGACCAATAAAACCCAAGTGCAGTGTGAGGAGAGGCCCGCAGAGAAGAGTCTTGGAAGCTGAGGGGAGGTGACCTCAGCAGCACAGTGGACAGCGGTGCCAGTGACTTGGGAAGGTCAGAAAACAGAAGATGGAAAGTGGGTTTGGAAACCAGGGAGACCTGGGGAGAGCAGGTTGGCCGCAGCGGCAGGAGCTGGAATGGGAGGGGGTGCATGAGGCTGAGTGTGGCGCATCCTCCTCGGGGCTGAGATGGATTTTACTTGTCTTGGGTTCCCCACGGCTGTCACAGGGCAGTGTCTGAGTTCATTCGTCTTTTTCCTTCAGGAAGTCTGGGTGTAAAGGGATGGAGAGAGGTGAGGTGTGTGCAGTAAGAGGATTTCTCAAGGATGGGACAGGAAGGCCTTGGAGCTTTGGCTTCCTCCTGTGAACTTGTGGGGTGGGGAGCCTGGTGCACCAACCTTTGGGACTTGAGGGAGTAGTATCAGGATGTGGGATTGAGCCCTGGACCTTTTTTCTAGAAAGAGGAAAAAAATGAAGGGAGGAGGAGGAGGAAGCTGGGGAGATCACACCTTTGATTTTCTTGTTCCTGGAAAGTGAAAGGAAGTTCACCTGCTATGAGTGAGAAGGTGGACACACTGGGTGGGGATGAGGTGAGTGACATGAGCTTAGGAAAGTTGCTGAGGTAATTGGTTGAGAGAGGTGTTCAAATAAAAGTAATGCAATTGGCAAAAACTGTTACTAAGACTTTGTAGAGGCACAAATCAGTGACATGGCAGCATCTTCTTTCACAGTAATCAACTGCCAGATTGCAGGGAGCCCTGATACCAGCCTAAGGAGTGTGAGTTTCTCCTCTAGGCCCACAGGTCCCCAACCTCACTCCTCCGAAGACTCTACTGGAGATCATCTGTGATGCGCAGATACCCAGACTCACTGCCCCGAGACTCAGATTCCCTGGGTGGGGAGGTCTGGGGATCTCTGCTTGTAATCAGCTCCCTAGAGGTTCCCATGTAGCCGGATAAGTATTGTCAGAACACTGAAGATTTTTGAAAAATGAAAAAGAGAAGGTTGGAGATGTGTCTTCAGAAGACTACTAAGGGTGCTGGGTAGAGGAGGGACCAGAGGCAGGGAGATGAGGTAGGAAACTGCTATTATTTGTCAGGGAAATTGCAATCAAGAAATGAGTTAGAACAGGGAAAACACAGAGGCAGGGGAGAGGTGGAAGGGGGAGGAAAGGAGTAGTGACAATTCCAGGGTGTATGCTCACCCAAATCTAGAAGTAATTGAGCAAATGTTTTCTGGGCATTAGAGAAGGCAACTAGAACAAACAGGAATCCTTGCCTTGGTGAAATGTATTTGAACTGGGTCAGAAATGAGGCCATTGGGTATCAAGCCTTAACTCCAGCGCCCCCTGGAGGTCGCTGATGTGGCTCCAGGCTGACCTGCTCCTGTCAAAGAATATTGAGCAAGATGCCTCTCATGGAATGTTCTGGGACCTTAAAACAGATACCCAAGTATTCCCCCTGATTTCATGGTTCCCAGAAGCTCTATGGGGAAGAAATTGTACGTAATTCACAACTGAGATTTAGACATAAGTTGAATAGTGTAATGGACGTTGAGTTAACCGAGGTAATGAAGTAGTGAGACACAGGTGCCCCTGAAATAAACTCACATTGAGGGAAGAGGCTGACAATGTGGATCAGTCTGTAAACAAGGCAAAAATACAATAGGGAGTAAGGGTTGTGTGTCAGTTCAAGACTGTACTTTTACCTGGCCCAGCGCCATGTTGGGGTATTTGTGTTCTCCAGGAAGTAGAAAGGAAAGAACTGAGTGATTAGGGACCTAGAAGACTAATTTGAGACATTCCTCTTGATGAACTGTTCTCTAGGGTAGTCCTCTGAAAGAGCTGTTCTCTAGTGGATCTCCCTGAATGAACTGTTCTCTAGGAGCACTTGACCCTTTTCTGTGTTTGTTTTTTGTTTTGTGTTTGTGTTTGTTTTTGAGACAGGTTCTCGCTCTGTCTCCCAGGCTGGAGTGCTGTGGCGCCATCATGACTCACTGCAGCCTCAACCTCCTGGGCTCAAGTGATCCTCCTGCCTCAGCCTCCCATGTAGCTAGAACTACAGATACATGTACCACCATGTCTGGCTAATTTATTTTTCTTTTTAGAGATGGGTTCTCACTATGTTGCCCAGGCTGGTCTCGAAACCCTGGGCTCAAGTGATCCTCACGCCTCAGCCTCCCAAAGTGCTAAGATTATAGGCATGACCACCATGCCTGGCCTTTTCTGCCTTCCGAGAAGGAAAAAGGTACTGGTGGCAGAGATCCAAAAGAAAAGTTGCCAGTGGCAGTGTGGAAATTGACCTGAGAACAACAGAACAAGCTGGGGCACAAATGCAAAGATGCAGAGGGAGGCAACATCTGGTTATCTGTGAGACCTTCATGGGACCTGAAGACACATCCTTTTGGAAAAGGATGGGATTTCTACTACTCAAGCATGTAGGGGCTCAGGATATTATGTAAATATGAAGATTTTGAGTTTTTGTAAGTGAGGTAAAAAAAATACCCAGGTTATTTACAGAATAAGACATGTCAAGCTCTCTTCATTTTCTTTGTATTTTCATGAAATAAAGGTATTAGATTAACAGGCCACCATAATGCCATTGTCTGTATATCTTAATTTCAAGATATTATTTGAGTAATTTTTGCATCCTTTGTATCAAGATAGAACTTTGAAAAGACAGGTAATTTCACAGTTGATTAAATATTCTTTGCCCAAATTACTTTTGGTTAAAATTTCTCCTATATGTGCTACAGAGTGCAAACTCTGTCTCCCTGCCATTCCGCTATATACTTACTAATTATTATTTTATTCAAGATCATGCATGCTCTACTTGAAGGTCTATCTTTTCAGTGCTACCCTTACCCACTAGCCTAATCACATTATATCTATTTTCAACATCTAGGAATCAATTACGTAGTGAACATGCCTAAGAAATAATAATCTGGGCAGATGCAGTGGCTCAGGCCTGTAATCCCAGCACTTTGAGAGGCTGAGCGGGTGGATCACTTGAGGTCAGGAGTTGGTCAAGTGCTCCTAGAGAACCAGCCTGACCAACATGGAGAAACCTTGTCTCTACTGATAATACAAAAATTAGCCAGGTGAGGTGGCAGGCACCTATAATCCCAGCTATTCGGGAGGCTGAGGAAGGAGAATTGCTTGAACCCCTGAGGTGGAGGTTGCAGTGAGCCAATATTGCGCCACTGCATTCCAGACTTGGCAACAGAGCGACACTCCACCTCAACAAAAAGAAAGAAAGAGCGAGATTACGTCTCACAATCTCAAATGCTATTTCATTATTTTCCTTCCCCACTCGTAGTCCAGCCTAAGGTGAACGTTTCCCCCTCCAAGAAGGGGCCCCTGCAGCACCACAACCTGCTTGTCTGCCACGTGACAGATTTCTACCCAGGCAGCATTCAAGTCCGATGGTTCCTGAATGGACAGGAGGAAACAGCTGGGGTCGTGTCCACCAACCTGATCCGTAATGGAGACTGGACCTTCCAGATCCTGGTGATGCTGGAAATGACCCCCCAGCAGGGAGACGTCTACATCTGCCCAGTGGAGCACACCAGCCTGGACAGTCCTGTCACCGTGGAGTGGAGTGAGTCTCTGATGACCGT

**Comment by mhalagan** [comment]
This would be an issue with the `SeqAnn` package, not the `pygfe` package so debug this in the `SeqAnn` package. Figure out what DPB1 allele (DPB1*11:01:01:01 ?) this sequence corresponds to and then run that known sequence through the `SeqAnn` algorithm. It should quickly annotate the sequence since it will exactly match with an already observed sequence. Then remove chunks of that sequence that aren't in your original sequence and rerun to see if it successfully annotates the sequence. Do that until you get the same error you got above. By looking at the annotations that are produced it should give you an idea of what's causing the error.
