### ISSUE TITLE
running seq2gfe from docker gives an error

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-gfe#38]
This may mean the docker image is out of sync with seqann

```docker run -it --rm -v $PWD:/opt nmdpbioinformatics/py-gfe seq2gfe -f /opt/A.fasta -l HLA-A
******************** HLA:HLA00001 A*01:01:01:01 3503 bp ********************
Traceback (most recent call last):
  File "/usr/local/bin/seq2gfe", line 90, in <module>
    main()
  File "/usr/local/bin/seq2gfe", line 79, in main
    print(gfe_name, f, ann.method, str(ann.annotation[f].seq), sep="\t")
AttributeError: 'Seq' object has no attribute 'seq'
```

**Comment by pbashyal-nmdp** [comment]
The error was due to biopython update. Fixed with the `nmdpbioinformatics/py-gfe:1.1.5` release.

Running
```
docker run --rm -v $PWD:/opt nmdpbioinformatics/py-gfe:1.1.5 seq2gfe -f /opt/A53R2A0K3H0M.fasta -l HLA-A
```
Gives:
```
******************** HLA:HLA00001 A*01:01:01:01 ********************
HLA-Aw2-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-4	five_prime_UTR	match	CAGGAGCAGAGGGGTCAGGGCGAAGTCCCAGGGCCCCAGGCGTGGCTCTCAGGGTCTCAGGCCCCGAAGGCGGTGTATGGATTGGGGAGTCCCAGCCTTGGGGATTCCCCAACTCCGCAGTTTCTTTTCTCCCTCTCCCAACCTACGTAGGGTCCTTCATCCTGGATACTCACGACGCGGACCCAGTTCTCACTCCCATTGGGTGTCGGGTTTCCAGAGAAGCCAATCAGTGTCGTCGCGGTCGCTGTTCTAAAGTCCGCACGCACCCACCGGGACTCAGATTCTCCCCAGACGCCGAGG

...

HLA-Aw2-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-4	exon_8	match	TGTGA
HLA-Aw2-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-4	three_prime_UTR	match	GACAGCTGCCTTGTGTGGGACTGAGAGGCAAGAGTTGTTCCTGCCCTTCCCTTTGTGACTTGAAGAACCCTGACTTTGTTTCTGCAAAGGCACCTGCATGTGTCTGTGTTCGTGTAGGCATAATGTGAGGAGGTGGGGAGAGCACCCCACCCCCATGTCCACCATGACCCTCTTCCCACGCTGACCTGTGCTCCCTCTCCAATCATCTTTCCTGTTCCAGAGAGGTGGGGCTGAGGTGTCTCCATCTCTGTCTCAACTTCATGGTGCACTGAGCTGTAACTTCTTCCTTCCCTATTAAAA
Total Length: 3503
```
